query JurorsAppealReminderV2(
    $reminderDeadline: BigInt!,
    $timeNow: BigInt!,
    $blockHeight: Int!,
    $idLast: ID!,
    $blockLast: BigInt!){
    disputes(
        first: 1000,
        where: {
            id_gt: $idLast,
            period: appeal,
            periodDeadline_lte: $reminderDeadline,
            lastPeriodChangeBlock_gt: $blockLast
        },
        block: {number: $blockHeight},
        orderBy: id,
        orderDirection: asc) {
            id
            jurors{
                id
            }
            periodDeadline
    }
}