query AppealableDisputes($timestamp: BigInt!){
  disputes(first: 1000, where: {period: appeal, lastPeriodChange_gt: $timestamp}, orderBy: lastPeriodChange) {
    lastPeriodChange
    disputeID
    currentRulling
    arbitrable {
        id
    }
  }
}