query JurorsCommit(
    $blockHeight: Int!,
    $indexLast: BigInt!){
    draws(
        first: 1000,
        where: {
            disputeID_: {
                period: commit,
                periodCommitIndex_gte: $indexLast
            },
            round_:{
                active: true
            }
        }, 
        block: {number: $blockHeight},
        orderBy: disputeID__periodCommitIndex, 
        orderDirection: asc) {
        address
        disputeID{
            periodDeadline
            periodCommitIndex
            id
        }
    }
}