query JurorsDrawn(
    $blockHeight: Int!,
    $indexLast: BigInt!){
    draws(
        first: 1000, 
        where: {
            index_gte: $indexLast,
            disputeID_: {
                period: evidence,
            },
            round_:{
                active: true
            }
        }, 
        block: {number: $blockHeight},
        orderBy: index, 
        orderDirection: asc) {
            address
            index
            disputeID{
                id
                periodDeadline
                subcourt{
                    hiddenVotes
                }
            }
    }
}