query JurorsVote(
    $blockHeight: Int!,
    $indexLast: BigInt!){
    draws(
        first: 1000,
        where: {
            disputeID_: {
                period: vote,
                periodVoteIndex_gte: $indexLast
            },
            round_:{
                active: true
            }
        }, 
        block: {number: $blockHeight},
        orderBy: disputeID__periodVoteIndex, 
        orderDirection: asc) {
        address
        disputeID{
            periodVoteIndex
            periodDeadline
            id
            subcourt{
                hiddenVotes
            }
        }
    }
}